
MOVE_NULL = (0, 0)
MOVE_RIGHT = (1, 0)
MOVE_UP = (0, -1)
MOVE_LEFT = (-1, 0)
MOVE_DOWN = (0, 1)

MOVES = [
    MOVE_NULL,
    MOVE_RIGHT,
    MOVE_UP,
    MOVE_LEFT,
    MOVE_DOWN
]

# Convenience, if you want a square board.
BOARD_SIDE_LENGTH = 3

BOARD_WIDTH = BOARD_SIDE_LENGTH
BOARD_HEIGHT = BOARD_SIDE_LENGTH

SPAWN_FREQUENCY = 1.0

AVOID_CRASHES = True